using System;

public enum SkillLogicId
{
	unknow,
	BornSkill,
	OccupiedSkill,
	CapturedSkill,
	BeCapturedSkill,
	TeamInitiativeSkill,
	JinGuSkill,
	TianShangSkill,
	DuWuSkill = 11,
	FengBaoSkill,
	SiShiSkill = 16,
	ChouXinSkill,
	NiePanSkill,
	ChongWangSkill = 22,
	ChongDongSkill,
	QiXiSkill,
	YiHuaSkill = 29,
	WenYiSkill,
	IntensifyAttackSkill,
	IntensifyHPSkill,
	IntensifySpeedSkill,
	IntensifyOccupidSkill,
	WeakenAttackSkill,
	WeakenHPSkill,
	WeakenSpeedSkill,
	WeakenOccupidSkill,
	HideStartSkill = 40,
	LasercannonSkill,
	InhibitSkill,
	SacrificeSkill,
	OverKillSkill,
	CloneToSkill,
	TreasureSkill,
	UnknownStarSkill,
	RotateSkill,
	MirrorSkill,
	DiffusionSkill,
	CurseSkill,
	CannonSkill
}
